service: private-fs

plugins:
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  apiKeys:
    - fs
  usagePlan:
    quota:
      limit: 100000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  environment:
    FS_BUCKET:
      Ref: FS
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:GetObject'
      Resource:
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: FS
              - /*

functions:
  fs:
    handler: bucket-proxy.handler
    warmup: true
    events:
      - http:
          path: fs/{file+}
          method: get
          private: true

resources:
  Resources:
    FS:
      Type: AWS::S3::Bucket
      Description: files
      DeletionPolicy: Retain
